title: EcoBoard
description: Desciption!!
theme: just-the-docs

url: https://ecoboard.live

aux_links:
  Thingiverse Page: https://www.thingiverse.com/thing:6580828
  GitHub Repository: https://github.com/IanCavalluzzi/EcoBoard
